/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiLeadsIndexRouteImport } from './routes/api/leads/index'
import { Route as ApiLeadsGenerateRouteImport } from './routes/api/leads/generate'
import { Route as ApiLeadsIdRouteImport } from './routes/api/leads/$id'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsIndexRoute = ApiLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiLeadsGenerateRoute = ApiLeadsGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiLeadsIdRoute = ApiLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ApiAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/generate': typeof ApiLeadsGenerateRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/generate': typeof ApiLeadsGenerateRoute
  '/api/leads': typeof ApiLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/generate': typeof ApiLeadsGenerateRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/auth'
    | '/api/leads'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/leads/$id'
    | '/api/leads/generate'
    | '/api/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/auth'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/leads/$id'
    | '/api/leads/generate'
    | '/api/leads'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/api/auth'
    | '/api/leads'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/leads/$id'
    | '/api/leads/generate'
    | '/api/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiLeadsRoute: typeof ApiLeadsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/': {
      id: '/api/leads/'
      path: '/'
      fullPath: '/api/leads/'
      preLoaderRoute: typeof ApiLeadsIndexRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/leads/generate': {
      id: '/api/leads/generate'
      path: '/generate'
      fullPath: '/api/leads/generate'
      preLoaderRoute: typeof ApiLeadsGenerateRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/leads/$id': {
      id: '/api/leads/$id'
      path: '/$id'
      fullPath: '/api/leads/$id'
      preLoaderRoute: typeof ApiLeadsIdRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof ApiAuthRoute
    }
  }
}

interface ApiAuthRouteChildren {
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

interface ApiLeadsRouteChildren {
  ApiLeadsIdRoute: typeof ApiLeadsIdRoute
  ApiLeadsGenerateRoute: typeof ApiLeadsGenerateRoute
  ApiLeadsIndexRoute: typeof ApiLeadsIndexRoute
}

const ApiLeadsRouteChildren: ApiLeadsRouteChildren = {
  ApiLeadsIdRoute: ApiLeadsIdRoute,
  ApiLeadsGenerateRoute: ApiLeadsGenerateRoute,
  ApiLeadsIndexRoute: ApiLeadsIndexRoute,
}

const ApiLeadsRouteWithChildren = ApiLeadsRoute._addFileChildren(
  ApiLeadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiLeadsRoute: ApiLeadsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
