/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiLeadsIndexRouteImport } from './routes/api/leads/index'
import { Route as ApiLeadsGenerateRouteImport } from './routes/api/leads/generate'
import { Route as ApiLeadsIdRouteImport } from './routes/api/leads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsIndexRoute = ApiLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiLeadsGenerateRoute = ApiLeadsGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiLeadsIdRoute = ApiLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/generate': typeof ApiLeadsGenerateRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/generate': typeof ApiLeadsGenerateRoute
  '/api/leads': typeof ApiLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/generate': typeof ApiLeadsGenerateRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/leads'
    | '/api/leads/$id'
    | '/api/leads/generate'
    | '/api/leads/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/leads/$id' | '/api/leads/generate' | '/api/leads'
  id:
    | '__root__'
    | '/'
    | '/api/leads'
    | '/api/leads/$id'
    | '/api/leads/generate'
    | '/api/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLeadsRoute: typeof ApiLeadsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/': {
      id: '/api/leads/'
      path: '/'
      fullPath: '/api/leads/'
      preLoaderRoute: typeof ApiLeadsIndexRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/leads/generate': {
      id: '/api/leads/generate'
      path: '/generate'
      fullPath: '/api/leads/generate'
      preLoaderRoute: typeof ApiLeadsGenerateRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/leads/$id': {
      id: '/api/leads/$id'
      path: '/$id'
      fullPath: '/api/leads/$id'
      preLoaderRoute: typeof ApiLeadsIdRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
  }
}

interface ApiLeadsRouteChildren {
  ApiLeadsIdRoute: typeof ApiLeadsIdRoute
  ApiLeadsGenerateRoute: typeof ApiLeadsGenerateRoute
  ApiLeadsIndexRoute: typeof ApiLeadsIndexRoute
}

const ApiLeadsRouteChildren: ApiLeadsRouteChildren = {
  ApiLeadsIdRoute: ApiLeadsIdRoute,
  ApiLeadsGenerateRoute: ApiLeadsGenerateRoute,
  ApiLeadsIndexRoute: ApiLeadsIndexRoute,
}

const ApiLeadsRouteWithChildren = ApiLeadsRoute._addFileChildren(
  ApiLeadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLeadsRoute: ApiLeadsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
